# Master Configuration for Claude Vision & Hands
# Production-ready settings for autonomous AI automation

system:
  name: "Claude Vision & Hands"
  version: "2.0.0"
  mode: production  # development, staging, production
  log_level: INFO
  data_dir: "~/.claude-vision-hands"

# Security Configuration
security:
  enabled: true
  strict_mode: false  # Set to true for maximum security

  # Input Validation
  validation:
    command_injection: true
    sql_injection: true
    xss_protection: true
    path_traversal: true

  # Prompt Guard
  prompt_guard:
    enabled: true
    block_suspicious: true
    max_prompt_length: 10000

  # Rate Limiting
  rate_limiting:
    enabled: true
    default_rate: 60  # requests per minute
    default_burst: 10
    window_size: 60

    # Per-action limits
    action_limits:
      login: 5  # per 5 minutes
      api_call: 100  # per minute
      file_operation: 50  # per minute
      vision_analysis: 20  # per minute

  # Audit Logging
  audit:
    enabled: true
    log_dir: "~/.claude-vision-hands/logs"
    rotation: daily
    retention_days: 90
    log_format: json  # json or text

  # Allowed/Blocked Resources
  allowed_domains: []  # Empty = allow all
  blocked_domains:
    - malicious-site.com

  allowed_file_extensions:
    - .txt
    - .json
    - .yaml
    - .csv
    - .png
    - .jpg
    - .pdf

# Workflow Recorder Configuration
recorder:
  enabled: true
  auto_capture: false  # Set to true to record all actions

  storage:
    path: "~/.claude-vision-hands/recordings"
    max_workflow_size: 1000  # max actions per workflow
    compression: true

  screenshots:
    enabled: true
    quality: 85  # 1-100
    format: png  # png, jpg
    max_size_mb: 5

  generation:
    optimize: true
    extract_variables: true
    detect_loops: true
    remove_redundant: true

# AI Configuration
ai:
  provider: gemini  # gemini, claude, openai
  fallback: local  # local, none

  # Gemini Settings
  gemini:
    model: "gemini-2.0-flash-exp"
    api_key_env: GEMINI_API_KEY
    max_tokens: 8000
    temperature: 0.1
    timeout: 30
    rate_limit: 60  # requests per minute

  # Vision Analysis
  vision:
    max_image_size_mb: 20
    supported_formats:
      - png
      - jpg
      - jpeg
      - webp
    cache_results: true
    cache_ttl: 3600  # seconds

# Memory System Configuration
memory:
  enabled: true
  auto_store: true  # Automatically store successful actions

  # Storage
  storage:
    backend: chromadb  # chromadb, faiss
    path: "~/.claude-vision-hands/memory"
    max_size_mb: 500
    auto_cleanup: true

  # Embeddings
  embeddings:
    model: "sentence-transformers/all-MiniLM-L6-v2"
    device: cpu  # cpu, cuda, mps
    batch_size: 32

  # Search
  search:
    default_limit: 10
    min_score: 0.5
    max_results: 100

  # Retention
  retention:
    enabled: true
    retention_days: 30
    archive_old: true
    max_memories: 100000

  # Caching
  cache:
    enabled: true
    max_size: 1000
    ttl: 3600

# Autonomous Agent Configuration
agent:
  enabled: true

  # Decision Making
  decision:
    confidence_threshold: 0.7
    max_retries: 3
    timeout: 300  # seconds

  # Learning
  learning:
    enabled: true
    min_confidence_to_store: 0.6
    learn_from_failures: true

  # Strategies
  strategies:
    proven:
      enabled: true
      min_confidence: 0.8
      require_past_success: true

    exploratory:
      enabled: true
      min_confidence: 0.7
      max_risk: 0.5

    cautious:
      enabled: true
      gather_info_first: true
      fallback_enabled: true

  # Execution
  execution:
    max_iterations: 20
    parallel_actions: false
    save_checkpoints: true

# Browser Control Configuration (Future)
browser:
  enabled: false  # Not yet implemented
  headless: true
  timeout: 30
  user_agent: "Mozilla/5.0"

# Desktop Control Configuration (Future)
desktop:
  enabled: false  # Not yet implemented
  failsafe: true
  pause: 0.1

# Integration Configuration
integration:
  mcp:
    enabled: true
    host: localhost
    port: 8080

  api:
    enabled: true
    host: 0.0.0.0
    port: 8081
    cors_enabled: true

  webhooks:
    enabled: false
    endpoints: []

# Performance Configuration
performance:
  workers: 4
  max_concurrent_tasks: 10
  queue_size: 100

  cache:
    enabled: true
    backend: memory  # memory, redis
    max_size_mb: 100

  profiling:
    enabled: false
    output_dir: "~/.claude-vision-hands/profiles"

# Monitoring Configuration
monitoring:
  enabled: true

  metrics:
    collect: true
    interval: 60  # seconds
    retention: 7  # days

  health_check:
    enabled: true
    interval: 30
    endpoint: /health

  alerts:
    enabled: false
    channels: []  # email, slack, etc.

# Development Configuration
development:
  debug: false
  hot_reload: false
  verbose_logging: false

  testing:
    enabled: true
    coverage: true
    parallel: false

# Production Overrides
production:
  security:
    strict_mode: true

  performance:
    workers: 8
    max_concurrent_tasks: 20

  monitoring:
    enabled: true
    alerts:
      enabled: true
